version: '2'
services:
  nginx:
    image: nginx:1.13
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/sites-enabled/default.conf:/etc/nginx/sites-enabled/default.conf
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/ssl:/etc/nginx/ssl
      - ./config/nginx/auth:/etc/nginx/auth
    volumes_from:
      - appdata:ro
    depends_on:
      - php
    networks:
      - frontend
      - backend


  php:
    image: skloeck/mag-php-7:7.1
    volumes:
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
    volumes_from:
      - appdata
    env_file: .env
    depends_on:
      - appdata
      - cache
    user: www-data
    networks:
      - backend


  appdata:
    image: alpine:latest
    volumes:
      - ./config/appdata/startup.sh:/startup.sh
      - .:/var/www/html
    command: /bin/sh /startup.sh


  cache:
    image: redis:4.0.6
    networks:
      - backend


networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
